export const TRACK_CACHE_TTL_MS = 60_000;
export const MAX_TRACK_CACHE_ENTRIES = 120;
export const DOWNLOAD_PIPELINE_TIMEOUT_MS = 220_000;
export const MAX_STORED_DOWNLOAD_JOBS = 120;
export const DOWNLOADED_FILE_TTL_MS = 5 * 60_000;
export const DOWNLOADED_FILE_CLEANUP_INTERVAL_MS = 60_000;
